# Generated by Django 5.2.7 on 2025-10-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='adresse',
            field=models.CharField(max_length=100),
        ),
    ]
