# Generated by Django 5.2.7 on 2025-10-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(choices=[('Simple', 'Simple'), ('Double', 'Double'), ('Familiale', 'Familiale')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('caracteristiques', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='chambres/')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
