# Generated by Django 5.2.7 on 2025-10-23 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='image',
        ),
        migrations.CreateModel(
            name='ChambreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chambres/gallery/')),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chambres.chambre')),
            ],
        ),
    ]
