# Generated by Django 5.2.7 on 2025-11-25 15:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambres', '0002_remove_chambre_image_chambreimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chambre',
            options={'ordering': ['numero'], 'verbose_name': 'Chambre', 'verbose_name_plural': 'Chambres'},
        ),
        migrations.AlterModelOptions(
            name='chambreimage',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Image de chambre', 'verbose_name_plural': 'Images de chambres'},
        ),
        migrations.AddField(
            model_name='chambre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créée le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chambre',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifiée le'),
        ),
        migrations.AddField(
            model_name='chambreimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Uploadée le'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chambre',
            name='caracteristiques',
            field=models.TextField(help_text='Équipements et services disponibles', verbose_name='Caractéristiques'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='description',
            field=models.TextField(help_text='Description détaillée de la chambre', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='disponible',
            field=models.BooleanField(default=True, help_text='Cochez pour rendre visible sur le site', verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='numero',
            field=models.CharField(help_text='Identifiant unique de la chambre', max_length=10, unique=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='prix',
            field=models.DecimalField(decimal_places=2, help_text='Prix en Ariary', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix par nuit'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='type',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Double', 'Double'), ('Familiale', 'Familiale')], max_length=20, verbose_name='Type de chambre'),
        ),
        migrations.AlterField(
            model_name='chambreimage',
            name='chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chambres.chambre', verbose_name='Chambre'),
        ),
        migrations.AlterField(
            model_name='chambreimage',
            name='image',
            field=models.ImageField(help_text='Formats acceptés: JPG, PNG, WEBP', upload_to='chambres/gallery/', verbose_name='Image'),
        ),
    ]
