# Generated by Django 5.2.7 on 2026-01-29 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambres', '0003_alter_chambre_options_alter_chambreimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalerieItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0, help_text="ordre d'affichage")),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item de Galerie',
                'verbose_name_plural': 'Items de Galerie',
                'ordering': ['ordre', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accueil/')),
                ('description', models.CharField(max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalerieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galerie/', verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('ordre', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chambres.galerieitem', verbose_name='Item de Galerie')),
            ],
            options={
                'verbose_name': 'Image de galerie',
                'verbose_name_plural': 'Images de galerie',
                'ordering': ['ordre', '-uploaded_at'],
            },
        ),
    ]
